const MOVIES_API_URL = 'https://api.nomoreparties.co/beatfilm-movies';
const MAIN_API_URL = 'https://api.movies.pishchenko.nomoredomains.icu';
const MOVIES_IMAGE_URL = 'https://api.nomoreparties.co';

const SHORT_MOVIE = 40;

const CARDS_COUNT_MAX_WINDOW_SIZE = 16;
const CARDS_COUNT_MEDIUM_WINDOW_SIZE = 8;
const CARDS_COUNT_MIN_WINDOW_SIZE = 5;
const NEXT_CARDS_COUNT_MAX_WINDOW_SIZE = 4;
const NEXT_CARDS_COUNT_MEDIUM_WINDOW_SIZE = 2;
const NEXT_CARDS_COUNT_MIN_WINDOW_SIZE = 1;

const MAX_WINDOW_SIZE = 1141;
const MEDIUM_WINDOW_SIZE = 768;
const MIN_WINDOW_SIZE = 767;

export {
  MOVIES_API_URL,
  MAIN_API_URL,
  MOVIES_IMAGE_URL,
  SHORT_MOVIE,
  CARDS_COUNT_MAX_WINDOW_SIZE,
  CARDS_COUNT_MEDIUM_WINDOW_SIZE,
  CARDS_COUNT_MIN_WINDOW_SIZE,
  NEXT_CARDS_COUNT_MAX_WINDOW_SIZE,
  NEXT_CARDS_COUNT_MEDIUM_WINDOW_SIZE,
  NEXT_CARDS_COUNT_MIN_WINDOW_SIZE,
  MAX_WINDOW_SIZE,
  MEDIUM_WINDOW_SIZE,
  MIN_WINDOW_SIZE,
};
